### PR TITLE
fix: avoid trimming lines if we pass the option 'trimStringValues = false'

### PR DESCRIPTION
**Pull request by phtaylor**
We have XSLX files where cells contain spaces, and we want to keep those spaces as they have meaning.

### CODE REVIEW

**Comment by catamphetamine** [comment]
Can you provide more details on what’s the data and why would you want to
keep spaces

**Comment by phtaylor** [comment]
We are parsing XLSX files provided by a customer, that were exported from a third party software. Meaning that they were not authored by any human, and we have no control over the exporting/formatting.

The leading spaces encode a tree hierarchy in the data which our application needs to extract and use to rebuild its own internal tree.  

image

**Comment by mauroporras** [comment]
Thanks @catamphetamine.

I'm curious, why the "." for the commit messages?

Screen Shot 2022-05-26 at 20 24 08

**Comment by catamphetamine** [comment]
GitLab repo is the main one

**Pull request closed without merging**
